---
- name: Install nginx
  ansible.builtin.include_tasks: install.yml

- name: Nginx configure new site
  ansible.builtin.include_tasks: config.yml

- name: Allow ports though firewall
  ansible.builtin.include_tasks: ufw.yml
