---
- name: Deploy client list
  hosts: central
  become: true
  roles:
    - roles/nginx
    - roles/cloudflare
  vars:
    hostnames:
      - name: client-list.blazeclone.xyz
        port: 4000
      - name: client-list-api.blazeclone.xyz
        port: 4500
    dns_records:
      - name: client-list
        value: "{{ ansible_default_ipv4.address }}"
      - name: client-list-api
        value: "{{ ansible_default_ipv4.address }}"

  vars_files:
    - ../../vars/cloudflare/main.yml

  tasks:
    - name: Create volumes
      community.docker.docker_volume:
        name: mysql

    - name: Deploy client list containers
      community.docker.docker_compose:
        project_name: client-list
        definition:
          version: "3.9"
          services:
            react:
              image: ghcr.io/anthane-git/client-list-view:main
              container_name: cl-react
              ports:
                - 4000:5000
            laravel:
              image: ghcr.io/anthane-git/client-list-api:main
              container_name: cl-laravel
              ports:
                - 4500:80
            mysql:
              image: mysql/mysql-server:8.0
              container_name: cl-mysql
              ports:
                - 3306:3306
              environment:
                MYSQL_ROOT_PASSWORD: password
                MYSQL_DATABASE: client_list
                MYSQL_USER: root
                MYSQL_PASSWORD: password
              volumes:
                - mysql:/var/lib/mysql

          volumes:
            mysql:
              name: sail-mysql
