---
- name: Deploy identity provider
  hosts: central
  become: true
  roles:
    - roles/nginx
    - roles/cloudflare
  vars:
    hostnames:
      - name: identity-provider.blazeclone.xyz
        port: 5000
      - name: identity-provider-api.blazeclone.xyz
        port: 5500
    dns_records:
      - name: identity-provider
        value: "{{ ansible_ssh_host }}"
      - name: identity-provider-api
        value: "{{ ansible_ssh_host }}"
  vars_files:
    - ../../vars/cloudflare/main.yml

  tasks:
    - name: Create volumes
      community.docker.docker_volume:
        name: postgres

    - name: Deploy identity provider containers
      community.docker.docker_compose:
        project_name: identity-provider
        definition:
          version: "3.9"
          services:
            react:
              image: ghcr.io/anthane-git/identity-view:main
              container_name: idp-react
              ports:
                - 5000:5000
              environment:
                APP_API_ENTRYPOINT: https://identity-provider-api/v1
            nestjs:
              image: ghcr.io/anthane-git/identity-api:main
              container_name: idp-nestjs
              ports:
                - 5500:3000
              depends_on:
                - postgres
              environment:
                DATABASE_DOCKER_URL: postgresql://prisma:root@idp-postgres:5432/nest
                DATABASE_URL: postgresql://prisma:root@idp-postgres:5432/nest
            postgres:
              image: postgres:13
              container_name: idp-postgres
              restart: always
              ports:
                - 5432:5432
              environment:
                POSTGRES_DB: nest
                POSTGRES_USER: prisma
                POSTGRES_PASSWORD: root
              volumes:
                - postgres:/var/lib/postgresql/data

          volumes:
            postgres:
              name: nest-db
