---
- name: Install Prerequisites
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    state: present
    force_apt_get: true
  loop: ["aptitude"]

- name: Install Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop: "{{ packages }}"
