---
- name: Install prerequisites
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    force_apt_get: true
    state: present
  loop: ["aptitude"]

- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop: "{{ packages }}"
