---
- name: Install watchtower
  hosts: central
  tasks:
    - name: Deploy Watchtower
      community.docker.docker_container:
        name: watchtower
        command: |
          --interval 100
        image: containrrr/watchtower
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: always
