---
- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  listen: "Reload Nginx"

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  listen: "Restart Nginx"
