---
- name: Deploy Identity Provider
  hosts: cloud-central
  become: true
  roles:
    - roles/mysql
  vars:
    mysql_port: 3306
    mysql_db: idp
    mysql_db_user: idpadmin
    mysql_user_pass: idpadmin

  tasks:
    - name: Deploy Identity Provider
      community.docker.docker_compose:
        project_name: idp-view
        definition:
          version: "2"
          services:
            view:
              image: ghcr.io/anthane-git/identity-view:main
              ports:
                - 5000:5000
