---
- name: Deploy Identity Provider
  hosts: cloud-central
  tasks:
    - name: Deploy Identity Provider
      community.docker.docker_compose:
        project_name: idp-view
        definition:
          version: "2"
          services:
            view:
              image: ghcr.io/anthane-git/identity-view:main
              ports:
                - 5000:5000
