---
- name: Install docker
  hosts: cloud-central

  become: true
  tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: true

    - name: Add apt-key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add docker repo
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable

    - name: Install docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: true

    - name: Add user permissions
      ansible.builtin.command: usermod -aG docker root
      changed_when: false

    - name: Reset ssh connection for changes to take effect
      ansible.builtin.meta: reset_connection

    - name: Install python package manager
      ansible.builtin.apt:
        name: python3-pip

    - name: Install python sdk
      become_user: root
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose
