name: Run Linter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build 🚧

    steps:
      - uses: actions/checkout@v2

      - name: Run Ansible lint 🧼
        uses: ansible-community/ansible-lint-action@v6.6.1
        with:
          path: "playbooks/"
